export const countryCovidList = [{
    "Country": "Wallis and Futuna Islands",
    "Slug": "wallis-and-futuna-islands",
    "ISO2": "WF",
    "active":120,
    "confirmed":3000,
    "deaths":20,
    "recovered":2000
  },
  {
    "Country": "Malaysia",
    "Slug": "malaysia",
    "ISO2": "MY",
    "active":23,
    "confirmed":45,
    "deaths":40,
    "recovered":2100
  },
  {
    "Country": "Maldives",
    "Slug": "maldives",
    "ISO2": "MV",
    "active":90,
    "confirmed":234,
    "deaths":65,
    "recovered":867
  },
  {
    "Country": "Moldova",
    "Slug": "moldova",
    "ISO2": "MD",
    "active":354,
    "confirmed":1323,
    "deaths":565,
    "recovered":787
  },
  {
    "Country": "Pitcairn",
    "Slug": "pitcairn",
    "ISO2": "PN",
    "confirmed":132,
    "deaths":446,
    "recovered":787,
    "active":126,
  },
  {
    "Country": "Latvia",
    "Slug": "latvia",
    "ISO2": "LV",
    "confirmed":4545,
    "deaths":23,
    "recovered":2434,
    "active":798,
  },
  {
    "Country": "Mauritius",
    "Slug": "mauritius",
    "ISO2": "MU",
    "confirmed":132,
    "deaths":879,
    "recovered":878,
    "active": 65656,
  },
  {
    "Country": "Cayman Islands",
    "Slug": "cayman-islands",
    "ISO2": "KY",
    "confirmed":2467,
    "deaths":46,
    "recovered":34,
    "active":1,
  },
  {
    "Country": "Chile",
    "Slug": "chile",
    "ISO2": "CL",
    "confirmed":3434,
    "deaths":345,
    "recovered":3554,
    "active":7676,
  },
  {
    "Country": "Iceland",
    "Slug": "iceland",
    "ISO2": "IS",
    "active":4343,
    "confirmed":23434,
    "deaths":24343,
    "recovered":33434,
  },
  {
    "Country": "Ireland",
    "Slug": "ireland",
    "ISO2": "IE",
    "confirmed":224,
    "deaths":433,
    "recovered":4343,
    "active":3344,
  },
  {
    "Country": "Turkey",
    "Slug": "turkey",
    "ISO2": "TR",
    "confirmed":4437,
    "deaths":87,
    "recovered":12,
    "active":898,
  },
  {
    "Country": "China",
    "Slug": "china",
    "ISO2": "CN",
    "confirmed":23,
    "deaths":787,
    "recovered":3657,
    "active":76,
  },
  {
    "Country": "Guatemala",
    "Slug": "guatemala",
    "ISO2": "GT",
    "confirmed":576,
    "deaths":40,
    "recovered":15,
    "active":76,
  },
  {
    "Country": "Korea (South)",
    "Slug": "korea-south",
    "ISO2": "KR",
    "confirmed":6785,
    "deaths":657,
    "recovered":4657,
    "active":76,
  }];